### ISSUE TITLE
Chequear el conjunto de datos en la carga y no en la ejecución

### ISSUE THREAD

**Issue by alvarag** [dmacha27/TFG-SemiSupervisado#69]
Ahora mismo, la aplicación admite cualquier csv pero luego al ir a ejecutarlo nos dice:

![imagen](https://github.com/dma1004/TFG-SemiSupervisado/assets/9881614/e552b87a-928e-4f72-99ed-e843380a056f)

Creo que sería más adecuado chequear si tiene valores categóricos el csv/arff en la propia carga.

Otro detalle, el mensaje que muestra: 
Se han detectado características categóricas o indefinidas, es necesario que se aseguren características numéricas

Podría ser mejor algo como:
Se han detectado características categóricas o indefinidas, recuerde que los algoritmos solo soportan características numéricas.

**Comment by dma1004** [comment]
En cuanto al mensaje, mucho mejor, luego lo cambio!! 👍
